* Galileo's Middle Finger

** Front Matter

The author grew up with parents who were intellectuals, but radical Christians.
They had a copy of the encyclopedia next to their dinner table to settle
debates, but they filled their garage with protest signs for use outside of
abortion clinics. The author's upbringing taught her that intellectuals can
still be religious (though the author is an atheist).

She later went on to study history, get a PhD with a dissertation on the history
of intersex cases with doctors, and teach history while moonlighting as an
intersex rights advocate.

Later, she took on a scholarly project that investigated a controversy in the
transgender activism and research world. Michael Baily, a sex researcher at
Northwestern, pushed a theoryt that suggested in cases of men who become women,
"transgender isn't just about gender identity, but also about sexual
orientation--about eroticism" (quote from the book, not Baily). In this project,
she found that a small group of transgender rights activist tried to bury
Baily's theory by killing the messenger -- they held and aggressive campaign
that nearly ruined his reputation and life with false accusations about him,
instead of criticizing his work.

After publishing a 50,000 word paper on that, she found the tables had turned
and the group she once identified with---activists fighting against the
establishment---were now fighting against her. The story was "Alice Dreger
versus the rights of sexual minorities" and as hard as she tried to turn people
back to the truth, it didn't seem to matter.

#+BEGIN_QUOTE
In spite of how difficult some of it has been, this journey of discovery proves
something really important: Science and social justice require each other to be
healthy, and both are critically important to human freedom. Without a just
system, you cannot be free to do science, including science designed to better
understand human identity; without science, and especially scientific
understanding of human behaviors, you cannot know how to create a sustain ably
just system.

[...] I have come to understand that the pursuit of evidence is probably the
most pressing moral imperative of our time. All of our work as sscholars,
activists, and citizens of democracy depends on it. Yet it seems that,
especially where questions of human identity are concerned, we've built up a
system in which scientists and social justice advocates are fighting in ways
that poison the soil on which both depend.
#+END_QUOTE

The book gets its name from Galileo's actual middle finger. 100 years after he
was buried in a small grave (the grave of a heretic) his body was transferred to
a much larger, ornate grave (the grave of a hero). During that transfer, someone
cut off Galileo's middle finger and made a display out of it. This was in Italy,
so the middle finger doesn't (and didn't) have the significance it does in the
US, but the author thought it captured her view of Galileo well -- thinking
freely and always flipping the bird to the moral fashions of the time.

What was fundamentally unique about Galileo is that he thought and actively
argued that what mattered wasn't what the authorities /said/ was true, but what
anyone with the right tools could /show/ is true. When people said that the
world couldn't be spinning because anything not attached to the ground would be
flying about in the air, he asked them what happens when you drop a ball on a
moving ship (it falls down because of relativity). This fundamental concept of
/showing/ was the basis of all of his work (if any regular person had a good
enough telescope, they could see for themselves all of Galileo's astronomy
arguments).

While the period of Galileos' life is often considered the beginning of the
Scientific Revolution, what was actually happening was more more radical: it was
a revolution in /human identity/. When Galileo rejected the Vatican's
astronomical dogma, he wasn't just rejecting the "facts" about the stars and our
sun. He was also rejecting the Church's right to tell us who we are. For the
first time, people could see things for themselves and come to their own
conclusions, instead of being told how the world worked and who they were by the
authorities. Maybe the internet is signifying a similar shift in power today?

This idea of individualism led to the rise of democracy; the fact that many of
the founding fathers were science geeks was no coincidence.

I'm hooked.
