* Guns, Germs, and Steel
** Chapter 1: Up to the Starting Line
- About human history up until 13,000 years ago.
- A series of evolutionary phases of the predecessor to monkeys.
  - The predecessor's population split into four groups. Turned into Gorillas,
    chimps, humans, and maybe bonobos (I think? Would have to revisit book).
- Early on humans started colonizing different parts of world.
- One group split off into Europe, became Neanderthals.
- Remainder stayed in Africa. Early on, despite their bodies looking like ours,
  their brains were half the size.
- They later developed brains our size and started developing tools, e.g., to
  catch fish, build houses.
  - Building tools allowing them to live anywhere on earth (ex. houses let them
    live in cold climates)

The first chapter ended with an interesting question. Native Americans had a
vast head start to take over the world. Were twice as large, lots of resources,
etc. You could make a strong case for them to "win". A strong case can be made
for Africa, too. They've been there longer than anywhere else, giving them the
most time to develop. But what about Eurasia? Largest continent in world, people
have been there almost as long as Africa. Strong cases can be made for other
places, too, e.g., Australia (they had watercraft before anyone else). The rest
of the book investigates "why did Europe win?" and I'm interested to read more.

Other side note: The author inserts his own bias into the narrative and declares
that others are wrong. It adds character; I like it.
