* The Stranger

This is my first foray into absurdism -- the idea that we exist in a purposeless
and chaotic universe. In it, Meursault---the protagonist---lives a simple life
that lacks morals or ambitions. His lives his life accepting the truth for what
it is: the truth (and he doesn't read into it). He rejects religion and the only
fate he sees is death.

After his mother dies, he accepts the friendship of a neighbor that leads him
into a situation where he kills someone. During the resulting trial, he lacks
remorse, accepts the past for what it is (he's guilty), and tells the truth.
The judge portrays him as a menace against society and eventually gives him the
death penalty. Meursault's absurdity didn't have a place in their society

Once Meursault is in jail, waiting for the execution, his perspective of
absurdism becomes conscious. The only thing that's guaranteed is death, and it
doesn't matter whether it's in 50 years or now. He's terrified of the upcoming
execution, but he sees his fear as natural -- he'd be just as afraid in 50 years
when he's at death's door.

http://www.bibliofreak.net/2012/02/analysis-outsider-by-albert-camus.html is a
much longer (and better) analysis that better does the novel justice.
