* The Circle

Honestly was disappointed with this. The summary of the book got me super
excited -- techno-thriller set in a dystopia with themes of morality and
privacy, but it really, _really_ underdelivered.

The book is set in the near-future and follows Mae as and she works at The
Circle -- a data-obsessed Facebook and Google-esque mega-corp. She starts out as
a "Customer Experience" agent and is soon exposed to (and buys into) the
cult-like culture of The Circle. She's encouraged to stay after-hours for
company events and criticized for not being as active as others on the company's
internal social media. The Circle's "campus" takes Facebook and Google's
offerings to the extreme -- having free on-campus dorms and similarly outlandish
amenities, in addition to the standard free meals.

Two of The Circle's three founders have an extreme, totalitarian, and 1984-esque
view of transparency. Everything should be shared and all secrets are lies.
People shouldn't have anything to hide. As Mae becomes more integrated into The
Circle's culture, she buys into this view of transparency and decides to "go
transparent", sharing every waking moment of her entire life on a public
livestream. She quickly becomes The Circle's figurehead for their efforts to
"complete the circle" (i.e. have everything shared through The Circle and
control the flow of data) as they recruit thousands of politicians to also go
transparent.

Throughout Mae's time at The Circle, she has two primary love interests --
Francis and Kalden. Francis is a well-meaning coworker who leads the development
of child tracking devices. Kalden is a mysterious man Mae met at a company party
and subsequently went on multiple sex-caspades with. After her first night with
him, she couldn't find him on the company social network or contact him in any
way, adding to the mystery. Unsurprisingly, Kalden turns out to be the missing
third founder of the company and is against their push for all-seeing
transparency. He tries to convince her to use her livestream to turn the public
against The Circle's efforts, but to no avail. After she finds out he is Ty she
turns him in to the other two founders and the book ends.

After I was halfway through, I couldn't set the book down because I just wanted
to get it over with. The characters were shallow, the premise was implausible,
and the plot was very predictable. Going to read a Neal Stephenson next,
hopefully that'll make up for this.
